"""Dados simulados para a interface acadêmica do projeto."""

from amapa_politico_monitor.models.news_item import NewsItem


def get_mock_news() -> list[NewsItem]:
    """Retorna uma lista de notícias simuladas para demonstração."""
    return [
        NewsItem(
            id="mock-1",
            titulo="Governo do Estado do Amapá anuncia nova ação institucional",
            resumo="Reunião trata de medidas de transparência e gestão pública no estado.",
            fonte="Portal Institucional",
            url="https://exemplo.gov.br/noticia-1",
            data_publicacao="2024-01-15",
            municipios=["Macapá"],
            orgaos=["Governo do Estado do Amapá"],
            pessoas=["Secretário"],
            palavras_chave=["transparência", "governo"],
            categoria="Governo",
            impacto_institucional="Médio",
        ),
        NewsItem(
            id="mock-2",
            titulo="MP-AP reforça atuação em casos de licitação",
            resumo="Órgão destaca fiscalização em contratos públicos e controle institucional.",
            fonte="Agência de Notícias",
            url="https://exemplo.gov.br/noticia-2",
            data_publicacao="2024-01-14",
            municipios=["Santana"],
            orgaos=["MP-AP"],
            pessoas=["Promotor"],
            palavras_chave=["licitação", "contrato"],
            categoria="Ministério Público",
            impacto_institucional="Alto",
        ),
        NewsItem(
            id="mock-3",
            titulo="ALEAP discute orçamento e emenda parlamentar",
            resumo="Debate institucional reúne parlamentares e gestores sobre prioridades.",
            fonte="Assembléia Legislativa",
            url="https://exemplo.gov.br/noticia-3",
            data_publicacao="2024-01-13",
            municipios=["Macapá"],
            orgaos=["ALEAP"],
            pessoas=["Deputado"],
            palavras_chave=["orçamento", "emenda parlamentar"],
            categoria="Legislativo",
            impacto_institucional="Médio",
        ),
        NewsItem(
            id="mock-4",
            titulo="Prefeitura de Macapá realiza operação de transparência",
            resumo="Ação reforça divulgação de dados e acompanhamento de serviços públicos.",
            fonte="Prefeitura",
            url="https://exemplo.gov.br/noticia-4",
            data_publicacao="2024-01-12",
            municipios=["Macapá"],
            orgaos=["Prefeitura de Macapá"],
            pessoas=["Prefeito"],
            palavras_chave=["transparência", "operação"],
            categoria="Prefeitura",
            impacto_institucional="Médio",
        ),
        NewsItem(
            id="mock-5",
            titulo="TRE-AP acompanha agenda eleitoral no estado",
            resumo="Eleição e organização administrativa ganham destaque na agenda institucional.",
            fonte="TRE",
            url="https://exemplo.gov.br/noticia-5",
            data_publicacao="2024-01-11",
            municipios=["Oiapoque"],
            orgaos=["TRE-AP"],
            pessoas=["Tribunal"],
            palavras_chave=["eleição", "partido"],
            categoria="Eleitoral",
            impacto_institucional="Alto",
        ),
    ]
